### ISSUE TITLE
No way to access inventory

### ISSUE THREAD

**Issue by heyimkaze** [AzerothSixhten/Az_train#1]
So I am running QBCore Framework and trying to figure out. How to get the inventory of script to work. I am using qb-inventory which should work as intended. But it seems like the "helpnotification" does not work unless you are using ox-inventory on esx server.

Is there any way, this can be fixed somehow. I do like the script so far. But just not usefull, unless you can get into the inventory.

**Comment by Azerothwav** [comment]
Hello, I invite you to come on the official Discord to have a faster support,
https://discord.gg/DUDeCnansx
Sincerly, Azeroth
