### ISSUE TITLE
avancer avec le train

### ISSUE THREAD

**Issue by DARKAOFF** [AzerothSixhten/Az_train#2]
Hello j'ai eut un soucis, je viens de mettre le script:

- Après avoir sortie/rentrer le train + test coffre plus possible de faire avancer le train (mais je peux le faire reculer)

Je n'ai pas d'erreur en console

**Comment by DARKAOFF** [comment]
![image](https://user-images.githubusercontent.com/427770/227375787-d0648f17-4fd9-4a55-9abb-102c997829e4.jpeg)

**Comment by Azerothwav** [comment]
Bonjour, avez vous vérifier que dans votre configuration, la vitesse de votre train est bien configuré ?

**Comment by DARKAOFF** [comment]
Je n'ai pas changé les configurations de base

**Comment by Azerothwav** [comment]
Sur quelle version de onesync êtes vous ?

**Comment by DARKAOFF** [comment]
Tx 6359 et esx legacy 1.9.0

**Comment by Azerothwav** [comment]
Ce n'est pas votre version de onesync, c'est votre version de Tx et de votre framework que vous m'avez envoyée
